# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d78a1ee6bade69eedd20327c9fafbdb1a5313fbc37075f33fbcf1b5e22573d2b41ebffadd14b7026d9788eacc868dfee9a35157d929dfc8c540514b627e6450a

test:
  secret_key_base: 39b15b512a9535a62b5a91fcd50a358554a692450362fe8b2c146691ce931b1fe51724a22282fe06e1b2314ff54369358b587b67421eee1b79934cf0d43c8588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
